/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/_blank': RouteRecordInfo<'/_blank', '/_blank', Record<never, never>, Record<never, never>>,
    '/_tetsImageUpload': RouteRecordInfo<'/_tetsImageUpload', '/_tetsImageUpload', Record<never, never>, Record<never, never>>,
    '/customer': RouteRecordInfo<'/customer', '/customer', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/department': RouteRecordInfo<'/department', '/department', Record<never, never>, Record<never, never>>,
    '/employee': RouteRecordInfo<'/employee', '/employee', Record<never, never>, Record<never, never>>,
    '/joborder': RouteRecordInfo<'/joborder', '/joborder', Record<never, never>, Record<never, never>>,
    '/jobstatus': RouteRecordInfo<'/jobstatus', '/jobstatus', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/metalType': RouteRecordInfo<'/metalType', '/metalType', Record<never, never>, Record<never, never>>,
    '/productType': RouteRecordInfo<'/productType', '/productType', Record<never, never>, Record<never, never>>,
    '/unitType': RouteRecordInfo<'/unitType', '/unitType', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/_blank.vue': {
      routes: '/_blank'
      views: never
    }
    'src/pages/_tetsImageUpload.vue': {
      routes: '/_tetsImageUpload'
      views: never
    }
    'src/pages/customer.vue': {
      routes: '/customer'
      views: never
    }
    'src/pages/dashboard.vue': {
      routes: '/dashboard'
      views: never
    }
    'src/pages/department.vue': {
      routes: '/department'
      views: never
    }
    'src/pages/employee.vue': {
      routes: '/employee'
      views: never
    }
    'src/pages/joborder.vue': {
      routes: '/joborder'
      views: never
    }
    'src/pages/jobstatus.vue': {
      routes: '/jobstatus'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/metalType.vue': {
      routes: '/metalType'
      views: never
    }
    'src/pages/productType.vue': {
      routes: '/productType'
      views: never
    }
    'src/pages/unitType.vue': {
      routes: '/unitType'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
